### ISSUE TITLE
add ability to specify build tasks

### ISSUE THREAD

**Issue by gorangajic** [benoror/better-npm-run#18]
in the Readme I have saw that you have this example? 

``` javascript
    "build": [
        {
            "run": "build:dist"
        },
        {
            "run": "build:prod"
        }
    ],
```

is there some module to do this or it's just idea ?

I would like to have same ability so I can queue tasks one by one for build process

for example

``` javascript
   "betterScripts": {
   "build": ["clean", "webpack:production", "webpack:backend", "migrate"],
   "clan": {
       "command": 'rm -rf ./dist',
   },
   "wepback:production": {
        "command": "webpack",
        "env": {
            NODE_ENV: "production",
        }
   },
   "migrate": {
        "command": "node ./bin/migrate",
        "env": {
            "NODE_ENV": "production"
        }
   }
   ..etc
}
```

with this and [concurrently](https://www.npmjs.com/package/concurrently) I can completely replace grunt/gulp :smile:

**Comment by benoror** [comment]
I can't recall exactly why I did not implement it, but certainly that was the idea behind it.

Regarding [kimmobrunfeldt/concurrently](https://github.com/kimmobrunfeldt/concurrently) I'm not sure how bad it impacts **readibility** (CI server output for example), is it worth it?

**Comment by gorangajic** [comment]
Output is not that much readable but I use it in dev env to run more things in the same time, for example I use it to run server, webpack and [devurl](https://github.com/gorangajic/devurl) from the same terminal.

**Comment by benoror** [comment]
Ok, as an optional feature, and maybe also as a performance enhancenment.

Something like:

```
if (script instanceof Array && script.length) {
  script.forEach...
} else {
...
}
```

Maybe around here [lib/exec.js#L4](https://github.com/benoror/better-npm-run/blob/master/lib/exec.js#L4).

**Comment by benoror** [comment]
**OK, Probably a bigger & more robust refactoring is needed, considering the intention to switch to [child_process.spawn](https://github.com/benoror/better-npm-run/pull/14) (https://github.com/benoror/better-npm-run/issues/11)**

Also, an update to the README is needed

Thanks!

**Comment by benoror** [comment]
@gorangajic are you still interested in implementing this?

**Comment by gorangajic** [comment]
Sure, but I am currently busy. If someone else want to try it's free to do so

**Comment by benoror** [comment]
NP, I'll leave it open. If I find some spare time I will try it.

Cheers!

**Comment by amelon** [comment]
with parallelshell (https://github.com/keithamus/parallelshell) you can do that.
Not sure you have to develop it.

**Comment by vladimiry** [comment]
@amelon running tasks `one by one` and simultaneously (parallelshell) are different things.

**Comment by amelon** [comment]
@vladimiry sure - I probably missed the `one by one`
parallelshell is now merging (not really merging - read this https://github.com/mysticatea/npm-run-all/issues/10) with https://github.com/mysticatea/npm-run-all.

npm-run-all allow sequential or parallel tasks running

**Comment by OlegLustenko** [comment]
Hello, @benoror, did you implement this proposal?

**Comment by benoror** [comment]
@OlegLustenko  nope, it's still open for proposals, feel free to submit a PR

**Comment by benoror** [comment]
Is this still an issue? Otherwise we can close it, let me know 😄 Cheers!
