### ISSUE TITLE
How to pass through CLI arguments?

### ISSUE THREAD

**Issue by davezuko** [benoror/better-npm-run#20]
Hey there, hoping somebody can help me with this, as I could just be missing something obvious. If I have a better-npm script such as:

```
  "betterScripts": {
    "dev": {
      "command": "node --harmony bin/webpack-dev-server",
      "env": {
        "NODE_ENV": "development"
      }
    }
  }
```

and then npm scripts such as:

```
    "dev": "node ./node_modules/.bin/better-npm-run dev",
    "dev:debug": "npm run dev -- --debug"
```

Is there a way to get those CLI arguments to propagate through into the betterScripts command? This is a pattern I've been using to avoid repetition, and it was working until we switched to better-npm-run. Any advice on this? Even if it's just some generic CLI magic outside of better-npm-run.

**Comment by gorangajic** [comment]
It's not possible right now but I have added that ability to my pull request https://github.com/benoror/better-npm-run/pull/19

**Comment by davezuko** [comment]
Great, thank you so much @gorangajic.

**Comment by benoror** [comment]
Fixed via https://github.com/benoror/better-npm-run/pull/19
