### ISSUE TITLE
Execute multiple commands in one line

### ISSUE THREAD

**Issue by kolima** [benoror/better-npm-run#22]
"start-prod": {
      "command": "node server.builder && pm2 start server.js --name admin-prod",
      "env": {
        "NODE_ENV": "production"
      }
    }

**Comment by benoror** [comment]
huh?

**Comment by kolima** [comment]
@benoror I meant to use && in command, because executes only node server.builder from example or add new field - commands, which will take an array of commands.

**Comment by benoror** [comment]
This was already addressed in #18, have you seen it? PRs welcome!

I will close this issue. Cheers!
