### ISSUE TITLE
${PWD} doesn't work in 'command' argument

### ISSUE THREAD

**Issue by jacob-israel-turner** [benoror/better-npm-run#25]
I'm trying to run the following command:

`"command": "forever start -l ${PWD}/logs/forever.log -o ${PWD}/logs/out.log -e ${PWD}/logs/errors.log -a index.js",`

I get the following error:

`Error: ENOENT: no such file or directory, open '/Users/jacob/.forever/${PWD}/logs/forever.log'`

Indicating that the script is being executed in the wrong context and/or `${PWD}` isn't being evaluated as he present working directory.

I think I've found a workaround for now.

**Comment by benoror** [comment]
Hi @jacob-israel-turner I guess it won't work since that's an internal BASH variable:

http://tldp.org/LDP/abs/html/internalvariables.html

Can you share your workaround? And maybe document it in the README?

Cheers! :smile_cat:

**Comment by jacob-israel-turner** [comment]
I just moved the command to an `.sh` file and ran that.  I can certainly make a PR.

**Comment by benoror** [comment]
mmmm, just gave it a second thought and I will pass on your PR. 

I thought you had a different approach. I believe running shell scripts is such a common use case that there's no need to put it in the Readme.

Nevertheless this issue can be helpful for someone else in the same situation.

Thanks anyway for your PR and raising the question.

Kind regards!

**Comment by benoror** [comment]
Maybe this cam be added to a second file to avoid overload the Readme and just put a link to **advanced documentation**, something like **DOCS.md**, what do you think?

**Comment by jacob-israel-turner** [comment]
Might be sufficient to just link to this issue, unless you're planning on expanding the docs in the future anyways.
