### ISSUE TITLE
Cannot run cleanup on process exit

### ISSUE THREAD

**Issue by jacob-israel-turner** [benoror/better-npm-run#30]
When a Node process is about to close, certain signals are sent to the program that allow you to do any cleanup necessary before finally shutting down a process.  Examples [here](http://joseoncode.com/2014/07/21/graceful-shutdown-in-node-dot-js/).

While using `better-npm-run`, that is not allowed.  Once I kill the process (with either `ctrl-c` or `kill <pid>`), the process is closed and my cleanup is not allowed to run.

**Comment by benoror** [comment]
Hi @jacob-israel-turner I'm not sure how that involves `better-npm-run`, from what I understood you run your http server with `better-npm-run`, can you share your `package.json` script?

**Comment by benoror** [comment]
`better-npm-run` internally uses  [child_process' spawn](https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options), which creates a separate process. According to [the docs](https://nodejs.org/api/child_process.html#child_process_child_process):

> The child_process module provides the ability to spawn child processes in a manner that is similar, but not identical, to [popen(3)](http://linux.die.net/man/3/popen). This capability is primarily provided by the child_process.spawn() function

Originally I used [exec](https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback) but [it was changed](https://github.com/benoror/better-npm-run/commit/7cb31d640d5246e363c5146958378faab2a65360) as some people were having issues.

Maybe killing `better-npm-run` doesn't propagates properly to your child process (http server)?

**Comment by jacob-israel-turner** [comment]
Yes, I think that's the case.  I'm going to be playing with it a little this afternoon to see if I can find a solution.  Forgoing `better-npm-run` allows me to properly run cleanup, so it's either `better-npm-run`, or how I'm implementing `better-npm-run` that's causing the problem.

**Comment by gorangajic** [comment]
npm start have the same issue https://github.com/npm/npm/issues/4603

**Comment by jacob-israel-turner** [comment]
@gorangajic They might be related, but the issue I'm talking about has different results.  With the NPM issue, a process will _seem_ to exit, but if it is handling some cleanup, it could potentially keep running/printing to stdout until the process _actually_ exits (while, in the meantime, it appears you can run commands in the shell).

With the issue I'm talking about, the process appears to _actually_ exit upon initial `ctrl-c`.  If it doesn't actually exit, it definitely stops all printing.  I'd have to run some more tests to see if it actually exits or just goes silent.

**Comment by benoror** [comment]
@jacob-israel-turner cool :+1: ping me if you find out :smile:

**Comment by sampurcell93** [comment]
Any update on this? I too am worried about persistent invisible processes in my application.

**Comment by jacob-israel-turner** [comment]
I haven't had time to look into this more.  I ended up significantly refactoring how I'm handling processes and this issue is not longer pertinent to my work.  If anyone is still interested, see [https://github.com/benoror/better-npm-run/issues/30#issuecomment-172044717](my comment above) and try testing from there.

**Comment by benoror** [comment]
Is this still an issue? Otherwise we can close it, let me 😄 Cheers!

**Comment by jacob-israel-turner** [comment]
I'm no longer involved in any projects using `better-npm-run`, so I haven't worked on this since February or so. I'm sure it's still an issue, buy

**Comment by jacob-israel-turner** [comment]
But I won't be looking into this issue any more. Good luck!
(Writing comments on my phone can cause issues 😬)
