### ISSUE TITLE
Ability to specify .env file

### ISSUE THREAD

**Issue by mmahalwy** [benoror/better-npm-run#33]
Should be able to specify whether to use .env or .env.development, etc.

**Comment by benoror** [comment]
Is it a common practice? Do you have any info, links, specs?

**Comment by carnesen** [comment]
The dotenv module recommends against doing that https://www.npmjs.com/package/dotenv#should-i-have-multiple-env-files.

**Comment by benoror** [comment]
@carnesen thanks for the info!
