### ISSUE TITLE
Use 'dot-env' package

### ISSUE THREAD

**Issue by benoror** [benoror/better-npm-run#34]
Don't try reinvent the wheel and use [npmjs.com/package/dotenv](https://www.npmjs.com/package/dotenv) to replace [lib/dot-env.js](https://github.com/benoror/better-npm-run/blob/master/lib/dot-env.js)

Should be pretty straightforward :smile: 

Ref: https://github.com/benoror/better-npm-run/issues/33#issuecomment-180335816

**Comment by gorangajic** [comment]
https://github.com/benoror/better-npm-run/pull/35

**Comment by benoror** [comment]
released in: [0.0.7](https://github.com/benoror/better-npm-run/releases/tag/0.0.7)
