### ISSUE TITLE
Add a description field?

### ISSUE THREAD

**Issue by rafaelrinaldi** [benoror/better-npm-run#39]
Hey, I was just wondering if there's any interest in adding a new "description" field to the command options so we can also provide a better output for `npm run` when no arguments are given.

If there's interest, let me know and I can give it a shot.

Thanks!

**Comment by benoror** [comment]
Hey @rafaelrinaldi! Thanks for your suggestion!

I thinks it does no harm to have a description field as far as it's optional.

Fee free to submit a PR

Thanks in advance, cheers!

**Comment by benoror** [comment]
Hi @rafaelrinaldi,

Are you still working on this feature? Otherwise we can close the issue

Let me know, cheers!

**Comment by rafaelrinaldi** [comment]
Hey @benoror, I have not worked on this for a long time but I think I can give it a shot now. Feel free to close if you want 👍
