### ISSUE TITLE
Consider to add an alias to `better-npm-run` cli. Maybe something like `bnr`

### ISSUE THREAD

**Issue by royriojas** [benoror/better-npm-run#42]
Hi, would be you be open to add an alias to the `better-npm-run` cli. Something like `bnr`?

The issue here is that when you have several tasks running in parallel (or in sequence) having to 
writter `better-npm-run` several times makes the string really longer than it should be if the name of the alias would be something like `bnr`

The following npm script

```javascript
{
   "dev": "shell-exec 'better-npm-run start-dev' 'better-npm-run start-dev-api' 'better-npm-run start-dev-worker' 'better-npm-run start-dev-socket'",
}
```

can be somehow reduced to 

```javascript
{
   "dev": "shell-exec 'bnr start-dev' 'bnr start-dev-api' 'bnr start-dev-worker' 'bnr start-dev-socket'",
}
```

You don't need to change the name of binary, you just need to add another alias.

What do you guys think?

**Comment by benoror** [comment]
Wouldn't be better to use a [shell alias](http://www.tldp.org/LDP/abs/html/aliases.html)?

**Comment by royriojas** [comment]
benoror, well not really, because if you clone the project on a another computer now you have a manual step to create such an alias. I understand you don't see value on that, but this might be useful when you have tons of calls to `better-npm-run` in a single line :)

Thanks anyway.

**Comment by royriojas** [comment]
Also I'm not suggesting you to stop calling it `better-npm-run`. just in the `bin` section of your `package.json` add another alias

```javascript
"bin": {
    "bnr": "index.js",
    "better-npm-run": "index.js"
  },
```

**Comment by benoror** [comment]
Actually, that's not such a big deal, so why not! 😄

Could you submit a PR with the change, referencing this issue# in the commit title, like: "[#42] Add alias..."? Also some writing in the README.md explaining it would be great!

**Comment by royriojas** [comment]
sure. Will do it!
