### ISSUE TITLE
Inheriting stdin pipe as well

### ISSUE THREAD

**Issue by tomfin46** [benoror/better-npm-run#45]
Hey, looking to use better-npm-run to launch a script that's listening to stdin for user input however noticed you guys went with redirecting the stdin pipe whereas inheriting both the stdout and stderr ones.

Was wondering if there was a specific reason/use-case for this? or whether you'd accept switching to inheriting all the stdio pipes?

Thanks

**Comment by benoror** [comment]
Not really, PRs welcome! 😸

**Comment by benoror** [comment]
Fixed in: https://github.com/benoror/better-npm-run/pull/46
