### ISSUE TITLE
Add support for command string instead of sub-object.

### ISSUE THREAD

**Issue by galenandrew** [benoror/better-npm-run#47]
Hey @benoror! Cool package here! Would you be open to considering a PR that adds support for a command string vs sub-object?

For instance instead of:
```JSON
"betterScripts": {
    "some-nom-script": {
        "command": "node ./my-script.js"
    }
}
```

it could be…
```JSON
"betterScripts": {
    "some-nom-script": "node ./my-script.js"
}
```

The use case/value here is to simplify the `betterScripts` object when you don't have env variables to declare (because they are in a `.env` file).

Let me know, and if you're open to it I'll submit a PR.

**Comment by benoror** [comment]
Sure sounds good tome! Do you mind adjusting the README as well? Tha nks!

**Comment by benoror** [comment]
@galenandrew Andrew I just had a chance to review this, it's awesome! Sorry for the delay, and thanks for the contribution! Would yo be interested in becoming a repo maintainer?

**Comment by galenandrew** [comment]
@benoror thanks! As for being a repo maintainer, I'm happy to help anyway I can. Feel free to DM me on twitter or just comment here if there is a specific flow/process you follow (outside of the normal PR-based workflow).

**Comment by benoror** [comment]
@galenandrew  Just reviewing PRs whenever you have a chance, thanks  lot!
