### ISSUE TITLE
Parse env vars in betterScripts.taskName.env.envVarName

### ISSUE THREAD

**Issue by bguiz** [benoror/better-npm-run#49]
Given the following `betterScripts` section:

``` json
"test": {
      "command": "mocha --timeout 15000 --reporter mochawesome ./test/${NODE_ENV}.bootstrap.js ./test/**/*.spec.js",
      "env": {
        "MOCHAWESOME_REPORTNAME": "report-${NODE_ENV}",
        "MOCHAWESOME_REPORTTITLE": "Tests run in ${NODE_ENV}"
      }
    }
```

The value of `NODE_ENV` is substituted correctly in `betterScripts.test.command`, however, they remain verbatim in `betterScripts.test.env.MOCHAWESOME_REPORTNAME` and `betterScripts.test.env.MOCHAWESOME_REPORTNAME`.

Could we please get substitution going on inside of `env` from each task as well?

**Comment by benoror** [comment]
Hi @bguiz!

Never got the [requested changes](https://github.com/benoror/better-npm-run/pull/51#pullrequestreview-460344), are you still interested in this feature?

Otherwise we could close this :)

Let me know, cheers!
