### ISSUE TITLE
env: node\r: No such file or directory

### ISSUE THREAD

**Issue by kentcdodds** [benoror/better-npm-run#5]
Not sure why, but if I install via `npm install better-npm-run@0.0.1` I get this error when trying to run anything:

```
env: node\r: No such file or directory
```

However, it works fine if I install via `npm install benoror/better-npm-run#0.0.1`

Not sure what the problem is :-(

**Comment by benoror** [comment]
I tried both cases in a Win32 and a Linux vm and it works ok with:
- node 0.10.36 & npm 1.4.28
- node 0.12.4 & npm 2.10.1

**Comment by christianharke** [comment]
Same problem here. Installed via `npm install better-npm-run@0.0.1` and running `better-npm-run anyscript` will end in `env: node\r: No such file or directory` (Mac OS X) and `CommandNotFoundException` (Windows). Running as follows works fine:

````
$ node ./node_modules/better-npm-run anyscript
running better-npm-run in C:\path\to\project\root
...
```

Tested on
* Mac OS X & node 0.12.7 & npm 2.13.5
* Windows 10 & node 0.12.7 & npm 2.11.3

**Comment by danielstefanovic** [comment]
Same issue on [Codeship](https://codeship.com/) as well:

```
: No such file or directory

npm ERR! Linux 3.13.0-58-generic
npm ERR! argv "/home/rof/.nvm/versions/node/v0.12.7/bin/node" "/home/rof/.nvm/versions/node/v0.12.7/bin/npm" "run" "test:e2e"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
```

**Comment by benoror** [comment]
Turns out it worked in my local machine since I had an `npm link` to the the repo itself. I'll work on a fix asap

As a temporary fix you can run the locally installed bin as:

```
  "scripts": {
    "test": "node node_modules/.bin/better-npm-run test"
    "build": "node node_modules/.bin/better-npm-run build"
  },
```

**Comment by benoror** [comment]
According to contemporary npm wisdom, is it a good practice to run local `--save-dev` like that? Or is preferable to install packages globally?

**Comment by kentcdodds** [comment]
I think it's preferable to install the packages locally which will add the `bin` of the installed package to the `node_modules/bin` directory. Then in `npm scripts` the `node_modules/bin` directory is added to the `$PATH` when running a script so we can access those things.

**Comment by benoror** [comment]
I will close this issue now, as it is addressed by https://github.com/benoror/better-npm-run/pull/15
