### ISSUE TITLE
Auto-detect script from npm_lifecycle_event env var

### ISSUE THREAD

**Issue by cspotcode** [benoror/better-npm-run#52]
When better-npm-run is invoked via `npm run-script` it can autodetect which script to execute based on the `npm_lifecycle_event` environment variable.

For example, the following can be simplified:

```
"scripts": {
  "test": "better-npm-run test"
},
```

...to this:

```
"scripts": {
  "test": "bnr"
},
```

**Comment by benoror** [comment]
PR welcome! 😺 

### Github Etiquette

- https://stories.devacademy.la/how-to-use-github-like-a-proper-human-being-1a9c895c4e13#.4069xf24x
- http://chris.beams.io/posts/git-commit/
- https://github.com/agis-/git-style-guide

Let me know if you need any help! 😄

**Comment by benoror** [comment]
Hi @cspotcode!

are you still working on this feature?

Otherwise we could close this :)

Let me know, cheers!
