### ISSUE TITLE
Error propagation (stderr)

### ISSUE THREAD

**Issue by benoror** [benoror/better-npm-run#6]
In some scenarios errors might not be correctly raised, most probably because **stderr** is not handled correctly in the callback ([index.js#L28](https://github.com/benoror/better-npm-run/blob/master/index.js#L28)). [See node's exec docs](https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback).

**Comment by kentcdodds** [comment]
Thanks for looking into this. I think you've described the issue as thoroughly as I could.

**Comment by benoror** [comment]
@kentcdodds, I released a fix for stderr handling. I also created a repo to test all the possible outputs & errors:

https://github.com/benoror/better-npm-run-test-repo

**Comment by kentcdodds** [comment]
Fantastic! Thank you! :D
