### ISSUE TITLE
[Feature] Silent mode

### ISSUE THREAD

**Issue by ntucker** [benoror/better-npm-run#60]
Sometimes you have tooling you build around a script and you don't want extra output spewing out that you don't need. (In our case we are integrating with arcanist.) It would be lovely if we could silent the console.logs that happen in this project so we don't have to see that.

Maybe the authors have an opinion on what that option should be called?

**Comment by benoror** [comment]
> What you want is `npm run -s`. Reopen if you find a case where it doesn't work properly!

Reference: https://github.com/npm/npm/issues/6066#issuecomment-53939663

**Comment by ntucker** [comment]
No that silences npm, not the crap npm-better-run spews. I still get this:

```
running better-npm-run in /home/ntucker/robinhood-trader-web
Executing script: run-test

to be executed: node_modules/.bin/mocha --opts ./mocha.opts --recursive js/test -R xunit
```

**Comment by ntucker** [comment]
You have this line

```javascript
console.log('Executing script: ' + process.argv[2] + '\n');
```

**Comment by benoror** [comment]
PR welcome! 😺 

### Contribute

- Be **civil & polite**
- http://makeapullrequest.com/

### Github Etiquette

- https://stories.devacademy.la/how-to-use-github-like-a-proper-human-being-1a9c895c4e13#.4069xf24x
- http://chris.beams.io/posts/git-commit/
- https://github.com/agis-/git-style-guide

Let me know if you need any help! 😄

**Comment by benoror** [comment]
Closed via https://github.com/benoror/better-npm-run/pull/62
