### ISSUE TITLE
[Feature] cwd diretory

### ISSUE THREAD

**Issue by laggingreflex** [benoror/better-npm-run#61]
I have a use case where I need to do "cd xxx && yyy". I was wondering whether it could be achieved with this module by simply specifying the cwd directory, just like it does env variables?

**Comment by benoror** [comment]
have you tried using a npm script simply with `cd xxx && yyy` ?

**Comment by laggingreflex** [comment]
Yes. But it's an awkward syntax, and I thought it would be great having both this and cross-env removed and simply use `{env:xxx, cwd:yyy}`

**Comment by benoror** [comment]
I respectfully disagree good ol' shell syntax is awkward syntax ¯\_(ツ)_/¯

Gonna close the issue, nevertheless feel free to keep elaborating on your argument
