### ISSUE TITLE
Refactor silent flag using commander.js

### ISSUE THREAD

**Issue by benoror** [benoror/better-npm-run#63]
Refactor silent flag introduced in https://github.com/benoror/better-npm-run/pull/62  using [TJ's commander](https://github.com/tj/commander.js):

- http://tj.github.io/commander.js/
- https://developer.atlassian.com/blog/2015/11/scripting-with-node/

**Comment by ggilberth** [comment]
Have given this a go - #64

**Comment by benoror** [comment]
Closed via https://github.com/benoror/better-npm-run/pull/64
