### ISSUE TITLE
[Bug] Removing quotation marks from arguments

### ISSUE THREAD

**Issue by kdmitrijs** [benoror/better-npm-run#66]
Having an issue with quotation marks disappearing.

command: 
```
npm run test -- --grep "should do stuff"
```

npm script:
```
"test": "rm -rf ./tmp && mocha-webpack tests --opts tests/mocha.opts"
```

Normal npm behavior:
```
> rm -rf ./tmp && mocha-webpack tests --opts tests/mocha.opts "--grep" "should do stuff"
```

better-npm script:
```
"test": {
  "command": "rm -rf ./tmp && mocha-webpack tests --opts tests/mocha.opts"
}
```

better-npm behavior  (note the lack of `"` in the command arguments):
```
Executing script: test

to be executed: rm -rf ./tmp && mocha-webpack tests --opts tests/mocha.opts --grep should do stuff
...
Too many non-option arguments: got 3, maximum of 1
```

Workaround for npm is to use double quotes:
```
npm run test -- --grep "'should do stuff'"
```

**Comment by benoror** [comment]
Escaping quotes is expected behavior inside JSON files such as `package.json` afaik.

Feel free to open if you have more questions.

**Comment by kdmitrijs** [comment]
It is not inside the json file. I am talking about passing command line arguments to npm scripts.
Running the command `npm run test -- --grep "should do stuff"` requires quoting the last parameter to signify that it's not separate keywords (which is a perfectly sensible thing to do for any CLI program).
npm wraps every passed argument in quotes, which preserves the quoted arguments.
```
rm -rf ./tmp && mocha-webpack tests --opts tests/mocha.opts "--grep" "should do stuff"
```
But better npm loses them
```
rm -rf ./tmp && mocha-webpack tests --opts tests/mocha.opts --grep should do stuff
```
Meaning that you have to escape quotes in the command line.

**Comment by benoror** [comment]
@kdmitrijs we just released a new minor version, do you mind trying it? Cheers!
