### ISSUE TITLE
[Windows] Script fails when there are dots in the command path

### ISSUE THREAD

**Issue by kulmajaba** [benoror/better-npm-run#71]
betterScript from `package.json`:

    "dev-server": {
      "command": "./node_modules/.bin/webpack-dev-server --hot --inline --config webpack/development.js",
      "env": {
        "NODE_ENV": "development",
        "NODE_PORT": 3000
      }
    }

better npm run (more accurately spawn) throws an error on Windows with this script because of the `/.bin/` in the middle of the path. This happens with command prompt as well as bash. As with paths with spaces, this path should be wrapped with quotes. Writing the command like this to `package.json` fixes the issue:

    "command": "\"./node_modules/.bin/webpack-dev-server\" --hot --inline --config webpack/development.js"

My question is could the quote wrapping be added to better npm run? If I understand correctly, it would be a case of adding an additional check inside the `if (process.platform === 'win32') {}` in `/lib/exec.js` block and adding quotes if needed.

I can create a PR if I'm on the right track here.

**Comment by joshi-mehul** [comment]
Did you find solution? If not I can try and provide PR.

**Comment by benoror** [comment]
> Writing the command like this to package.json fixes the issue

@kulmajaba imho having to explicitly put the quotes in the JSON command sounds good to me, so anyone else can be certain that some spaces or special characters are there.

Also, in the case of spaces, how would you be certain if it's indeed an space inside the path or a separate argument? I mean, how would it differentiate something like `./foo "bar/.ba z"` from `./foo bar/.ba z` without explicit quotes?

Writing quotes is not that bad imo, as being explicit is a better practice.

Anyways, feel free to submit a PR if you find a better solution

**Comment by kulmajaba** [comment]
@benoror Fair enough, let's keep writing the quotes explicitly.

This might be a common issue for many people that are unfamiliar with the quirks of Windows so maybe we could mention this in the docs?

**Comment by benoror** [comment]
@kulmajaba yeah! do you mind adding it to the README? BTW, I don't think double quote scaping is exclusive to Windows 

Thanks, cheers!
