### ISSUE TITLE
License missing in npm package

### ISSUE THREAD

**Issue by char0n** [benoror/better-npm-run#81]
Hello, is is possible to incorporate the LICENSE file inside the npm package. Now it's missing. It's implied by MIT license that if licensed under the MIT the source code must be accompanied by full license text. If the license file is not in the npm package a lot of people cannot use it.

Thank you

**Comment by benoror** [comment]
@char0n good catch, would you mind creating a PR?

**Comment by benoror** [comment]
@char0n wait, it's here: https://github.com/benoror/better-npm-run/blob/master/LICENSE

**Comment by char0n** [comment]
Yes it's there (github repo), but it's not inside the npm package you're distributing. Can you pls publish the new version of the library which contains the license file in it ?

https://npm.runkit.com/better-npm-run - Click on `Browser Files`

**Comment by benoror** [comment]
@char0n oh sorry for that, I published a new version with the LICENSE included

Cheers!

**Comment by char0n** [comment]
Thank you very much for that.

**Comment by benoror** [comment]
thank you for reporting it 😄
