### ISSUE TITLE
🎁 better-scripts may be a better alternative

### ISSUE THREAD

**Issue by iamyoki** [benoror/better-npm-run#85]
Check it out: https://github.com/iamyoki/better-scripts

```json
{
  "scripts": {
    "scripts": "better-scripts"
  },
  "better-scripts": {
    "dev": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test"
  }
}
```

![image](https://user-images.githubusercontent.com/74389358/183866314-227ac1cb-00a8-415b-bfcf-50ff6addcf15.png)

**Comment by benoror** [comment]
Looks mostly sugar on top
